GRAPHRAG_LLM_MODEL: gpt-4o
GRAPHRAG_CLAIM_EXTRACTION_ENABLED: False
INPUT_DIR: "./artifacts"
COMMUNITY_LEVEL: 2
GRAPHRAG_API_BASE: ***
GRAPHRAG_OPENAI_API_VERSION: 2024-05-01-preview
GRAPHRAG_DEPLOYMENT_NAME: ***
GRAPHRAG_API_KEY: ***

EMBEDDING_API_KEY: ***
GRAPHRAG_EMBEDDING_MODEL: text-embedding-ada-002
EMBEDDING_API_VERSION: 2023-05-15
EMBEDDING_DEPLOYMENT_NAME: ***
GRAPHRAG_EMBEDDING_API_BASE: ***